import type { DecryptedVault } from "@/types/vault";
import { cryptoService } from "@/hooks/useCloudStore";
import { argon2id } from "hash-wasm";

export const base64ToUint8Array = (base64: string): Uint8Array => {
  const binaryString = atob(base64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
};

export const uint8ArrayToBase64 = (bytes: Uint8Array): string => {
  let binary = "";
  const len = bytes.byteLength;
  for (let i = 0; i < len; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
};

const encryptWithKey = async (key: CryptoKey, plaintext: Uint8Array) => {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const encrypted = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv },
    key,
    plaintext,
  );
  const encryptedBytes = new Uint8Array(encrypted);
  return {
    iv: uint8ArrayToBase64(iv),
    tag: uint8ArrayToBase64(encryptedBytes.slice(encryptedBytes.length - 16)),
    ciphertext: uint8ArrayToBase64(
      encryptedBytes.slice(0, encryptedBytes.length - 16),
    ),
  };
};

const decryptWithKey = async (
  key: CryptoKey,
  encrypted: any,
): Promise<Uint8Array> => {
  const iv = base64ToUint8Array(encrypted.iv);
  const ciphertext = base64ToUint8Array(encrypted.ciphertext);
  const tag = base64ToUint8Array(encrypted.tag);

  const combined = new Uint8Array(ciphertext.length + tag.length);
  combined.set(ciphertext);
  combined.set(tag, ciphertext.length);

  const decrypted = await crypto.subtle.decrypt(
    { name: "AES-GCM", iv, tagLength: 128 },
    key,
    combined,
  );
  return new Uint8Array(decrypted);
};

export const derivateKek = async (
  password: string,
  saltBase64: string,
): Promise<string> => {
  const saltBytes = base64ToUint8Array(saltBase64);
  const hashHex = await argon2id({
    password,
    salt: saltBytes,
    iterations: 3,
    memorySize: 65536,
    parallelism: 1,
    hashLength: 32,
    outputType: "binary",
  });

  const rawKeyBytes = new Uint8Array(hashHex);
  const kekBase64 = uint8ArrayToBase64(rawKeyBytes);
  rawKeyBytes.fill(0);
  return kekBase64;
};

export const generateDek = (): string => {
  const bytes = crypto.getRandomValues(new Uint8Array(32));
  return uint8ArrayToBase64(bytes);
};

export const encryptDek = async (
  dekBase64: string,
  kekBase64: string,
): Promise<string> => {
  const rawDek = base64ToUint8Array(dekBase64);
  const rawKek = base64ToUint8Array(kekBase64);

  const KEK = await crypto.subtle.importKey(
    "raw",
    rawKek,
    { name: "AES-GCM" },
    false,
    ["encrypt"],
  );
  rawKek.fill(0);

  const encryptedData = await encryptWithKey(KEK, rawDek);
  rawDek.fill(0);

  return JSON.stringify(encryptedData);
};

export const decryptDek = async (
  encryptedDekJson: string,
  kekBase64: string,
): Promise<string> => {
  const encrypted = JSON.parse(encryptedDekJson);
  const rawKek = base64ToUint8Array(kekBase64);

  const KEK = await crypto.subtle.importKey(
    "raw",
    rawKek,
    { name: "AES-GCM" },
    false,
    ["decrypt"],
  );
  rawKek.fill(0);

  const rawDekBytes = await decryptWithKey(KEK, encrypted);
  const dekBase64 = uint8ArrayToBase64(rawDekBytes);
  rawDekBytes.fill(0);

  return dekBase64;
};

export const encryptVault = async (
  vaultEntries: any[],
  folders: any[] = [],
): Promise<any> => {
  const foldersString = JSON.stringify(folders);
  const encryptedFolders = await cryptoService.encrypt(foldersString);
  const encryptedFoldersData = {
    iv: uint8ArrayToBase64(encryptedFolders.iv),
    tag: uint8ArrayToBase64(encryptedFolders.tag),
    ciphertext: uint8ArrayToBase64(encryptedFolders.ciphertext),
  };

  const entries: { [uuid: string]: any } = {};
  for (const entry of vaultEntries) {
    const entryString = JSON.stringify(entry);
    const result = await cryptoService.encrypt(entryString);
    entries[entry.id] = {
      iv: uint8ArrayToBase64(result.iv),
      tag: uint8ArrayToBase64(result.tag),
      ciphertext: uint8ArrayToBase64(result.ciphertext),
    };
  }

  return { folders: encryptedFoldersData, entries };
};

export const decryptVault = async (vault: any): Promise<any> => {
  const decryptedFoldersString = await cryptoService.decrypt(
    base64ToUint8Array(vault.folders.ciphertext),
    base64ToUint8Array(vault.folders.iv),
    base64ToUint8Array(vault.folders.tag),
  );
  const folders = JSON.parse(decryptedFoldersString);

  const entries: any[] = [];
  for (const uuid of Object.keys(vault.entries)) {
    const encryptedEntry = vault.entries[uuid];
    const decryptedEntryString = await cryptoService.decrypt(
      base64ToUint8Array(encryptedEntry.ciphertext),
      base64ToUint8Array(encryptedEntry.iv),
      base64ToUint8Array(encryptedEntry.tag),
    );
    entries.push(JSON.parse(decryptedEntryString));
  }

  return { version: vault.version || "1.0", folders, entries };
};

export const createInitialVault = async (): Promise<DecryptedVault> => {
  const now = () => new Date().toISOString();

  return {
    version: "1.0",
    folders: [
      {
        id: "folder-1",
        name: "Trabalho",
        icon: "bi-briefcase",
        colorHex: "#3498db",
      },
      {
        id: "folder-2",
        name: "Pessoal",
        icon: "bi-person",
        colorHex: "#2ecc71",
      },
      {
        id: "folder-3",
        name: "Finanças",
        icon: "bi-wallet2",
        colorHex: "#e74c3c",
      },
      {
        id: "folder-4",
        name: "Entretenimento",
        icon: "bi-tv",
        colorHex: "#9b59b6",
      },
      {
        id: "folder-5",
        name: "Importante",
        icon: "bi-shield-lock",
        colorHex: "#f1c40f",
      },
    ],
    entries: [
      // ==========================================
      // LOGINS (75 itens)
      // ==========================================

      // Trabalho / Dev Tools (1-15)
      {
        type: "login",
        id: "ent-1",
        title: "GitHub Corp",
        notes: "Conta corporativa vinculada ao e-mail da empresa.",
        foldersIds: ["folder-1"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "dev.master@empresa.com",
        password: "gHp_vX982jK1lsK73mNqPzW41A0xLq4bZ",
        url: "https://github.com",
      },
      {
        type: "login",
        id: "ent-2",
        title: "AWS Console",
        notes: "MFA obrigatório no celular físico.",
        foldersIds: ["folder-1", "folder-5"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "admin-prod",
        password: "C#v8!mP9$xLq2@zT1*kE",
        url: "https://aws.amazon.com",
      },
      {
        type: "login",
        id: "ent-3",
        title: "Jira Software",
        notes: "Acesso ao painel de sprints.",
        foldersIds: ["folder-1"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "colaborador.silva",
        password: "SenhaFraca123!",
        url: "https://atlassian.net",
      },
      {
        type: "login",
        id: "ent-4",
        title: "Slack",
        notes: "Workspace da empresa principal.",
        foldersIds: ["folder-1"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "silva@empresa.com",
        password: "p@sswordSlack99",
        url: "https://slack.com",
      },
      {
        type: "login",
        id: "ent-5",
        title: "Vercel",
        notes: "Login via GitHub.",
        foldersIds: ["folder-1"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "dev.master@empresa.com",
        password: "OAuth-Authenticated",
        url: "https://vercel.com",
      },
      {
        type: "login",
        id: "ent-6",
        title: "Figma",
        notes: "Projetos de UI/UX.",
        foldersIds: ["folder-1"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "designer.silva@empresa.com",
        password: "Vector#Art$2026",
        url: "https://figma.com",
      },
      {
        type: "login",
        id: "ent-7",
        title: "Bitbucket",
        notes: "Repositórios legados.",
        foldersIds: ["folder-1"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "silva_legacy",
        password: "mypassword123",
        url: "https://bitbucket.org",
      },
      {
        type: "login",
        id: "ent-8",
        title: "Sentry",
        notes: "Monitoramento de erros de prod.",
        foldersIds: ["folder-1"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "alerts@empresa.com",
        password: "S3ntry!Err0r$P4ss",
        url: "https://sentry.io",
      },
      {
        type: "login",
        id: "ent-9",
        title: "Linear.app",
        notes: "Gerenciamento de tasks rápido.",
        foldersIds: ["folder-1"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "silva@empresa.com",
        password: "Lin34r_Str0ng_P@ss",
        url: "https://linear.app",
      },
      {
        type: "login",
        id: "ent-10",
        title: "GitLab",
        notes: "Instância self-hosted da empresa.",
        foldersIds: ["folder-1"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "f.silva",
        password: "GitLab#Self#2026",
        url: "https://gitlab.empresa.com",
      },
      {
        type: "login",
        id: "ent-11",
        title: "DigitalOcean",
        notes: "Droplet de homologação.",
        foldersIds: ["folder-1"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "infra@empresa.com",
        password: "D0_Droplet$9911",
        url: "https://digitalocean.com",
      },
      {
        type: "login",
        id: "ent-12",
        title: "Cloudflare",
        notes: "Gerenciamento de DNS dos domínios.",
        foldersIds: ["folder-1", "folder-5"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "dns-admin@empresa.com",
        password: "CF_P4ssw0rd_#Secure",
        url: "https://cloudflare.com",
      },
      {
        type: "login",
        id: "ent-13",
        title: "Zoom",
        notes: "Reuniões com clientes.",
        foldersIds: ["folder-1"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "silva@empresa.com",
        password: "ZoomMeeting!1",
        url: "https://zoom.us",
      },
      {
        type: "login",
        id: "ent-14",
        title: "Notion Enterprise",
        notes: "Wiki interna da empresa.",
        foldersIds: ["folder-1"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "silva@empresa.com",
        password: "N0ti0n#Sh4r3d#K0wledge",
        url: "https://notion.so",
      },
      {
        type: "login",
        id: "ent-15",
        title: "Heroku",
        notes: "Apps antigos em node.",
        foldersIds: ["folder-1"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "velho.app@gmail.com",
        password: "herokupasswordold",
        url: "https://heroku.com",
      },

      // Pessoal e E-mails (16-30)
      {
        type: "login",
        id: "ent-16",
        title: "Google (E-mail Principal)",
        notes: "Conta que recupera tudo.",
        foldersIds: ["folder-2", "folder-5"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "G00gl3_Str0ng_!@#99",
        url: "https://accounts.google.com",
      },
      {
        type: "login",
        id: "ent-17",
        title: "Outlook (Antigo Hotmail)",
        notes: "Criado em 2010. Só lixo e spam.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "gatinho_loko2010@hotmail.com",
        password: "senhafofinha123",
        url: "https://outlook.live.com",
      },
      {
        type: "login",
        id: "ent-18",
        title: "ProtonMail",
        notes: "E-mail criptografado para assuntos sensíveis.",
        foldersIds: ["folder-2", "folder-5"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "shadow_user@proton.me",
        password: "Pr0t0n_S3cur3_V4ult_2026!",
        url: "https://mail.proton.me",
      },
      {
        type: "login",
        id: "ent-19",
        title: "Apple ID",
        notes: "Acesso ao iCloud e backup do celular.",
        foldersIds: ["folder-2", "folder-5"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "Iph0n3_S3cur3_Ch3ck",
        url: "https://appleid.apple.com",
      },
      {
        type: "login",
        id: "ent-20",
        title: "Microsoft Live Pessoal",
        notes: "Usado para o Windows do notebook.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@outlook.com",
        password: "MS_Notebook_Pass_$",
        url: "https://login.live.com",
      },
      {
        type: "login",
        id: "ent-21",
        title: "Gov.br",
        notes: "Senha do governo (nível ouro). Cuidado.",
        foldersIds: ["folder-2", "folder-5"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "12345678909",
        password: "GovBr#S3nha#F0rt3!",
        url: "https://sso.acesso.gov.br",
      },
      {
        type: "login",
        id: "ent-22",
        title: "Carteira Digital de Trânsito",
        notes: "Mesmo login do Gov.br.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "12345678909",
        password: "GovBr#S3nha#F0rt3!",
        url: "https://portaldetransito.gov.br",
      },
      {
        type: "login",
        id: "ent-23",
        title: "InSS Acesso",
        notes: "Consulta de tempo de contribuição.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "12345678909",
        password: "GovBr#S3nha#F0rt3!",
        url: "https://meu.inss.gov.br",
      },
      {
        type: "login",
        id: "ent-24",
        title: "Yahoo Mail",
        notes: "Totalmente abandonado, mas guardado.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: true,
        createdAt: now(),
        updatedAt: now(),
        username: "usuario_velho@yahoo.com.br",
        password: "yahoopassword",
        url: "https://mail.yahoo.com",
      }, // Exemplo de deletado
      {
        type: "login",
        id: "ent-25",
        title: "Linktree",
        notes: "Agregador de links do insta.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu_handler",
        password: "Linktr33_p@ss",
        url: "https://linktr.ee",
      },
      {
        type: "login",
        id: "ent-26",
        title: "Pinterest",
        notes: "Ideias de decoração para a casa.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "pinteresthome123",
        url: "https://pinterest.com",
      },
      {
        type: "login",
        id: "ent-27",
        title: "Reddit",
        notes: "Conta para ler subreddits de dev.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "code_ninja_2026",
        password: "R3ddit_Uniqu3_P@ss",
        url: "https://reddit.com",
      },
      {
        type: "login",
        id: "ent-28",
        title: "Quora",
        notes: "Inscrição automática indesejada.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "quorapassword99",
        url: "https://quora.com",
      },
      {
        type: "login",
        id: "ent-29",
        title: "Medium",
        notes: "Para ler artigos técnicos.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "MediumReader#2026",
        url: "https://medium.com",
      },
      {
        type: "login",
        id: "ent-30",
        title: "Trello Pessoal",
        notes: "Quadros de metas de ano novo vazios.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "trello_pessoal_pass",
        url: "https://trello.com",
      },

      // Redes Sociais (31-45)
      {
        type: "login",
        id: "ent-31",
        title: "Instagram",
        notes: "Conta pessoal.",
        foldersIds: ["folder-2"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "@john.doe.dev",
        password: "Insta!Ph0t0!2026!",
        url: "https://instagram.com",
      },
      {
        type: "login",
        id: "ent-32",
        title: "LinkedIn",
        notes: "Mantido atualizado para vagas.",
        foldersIds: ["folder-1", "folder-2"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "john-doe-professional",
        password: "LInkedIn#Work#Secure",
        url: "https://linkedin.com",
      },
      {
        type: "login",
        id: "ent-33",
        title: "Facebook",
        notes: "Só uso para o Marketplace e login em joguinhos.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "facebookpass123",
        url: "https://facebook.com",
      },
      {
        type: "login",
        id: "ent-34",
        title: "X / Twitter",
        notes: "Drama diário de tech.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "@johndoe_tech",
        password: "X_Twitt3r_S3cur3!$",
        url: "https://x.com",
      },
      {
        type: "login",
        id: "ent-35",
        title: "TikTok",
        notes: "Só assisto, não posto nada.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "@johndoe_lurker",
        password: "tiktokisaddictive1",
        url: "https://tiktok.com",
      },
      {
        type: "login",
        id: "ent-36",
        title: "Discord",
        notes: "Servidores de comunidades de programação.",
        foldersIds: ["folder-2", "folder-4"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "johndoe#9999",
        password: "Discord_G@m3r_P@ss",
        url: "https://discord.com",
      },
      {
        type: "login",
        id: "ent-37",
        title: "Twitch",
        notes: "Inscrições mensais usando Prime.",
        foldersIds: ["folder-4"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "twitch_watcher_9",
        password: "twitchpass456",
        url: "https://twitch.tv",
      },
      {
        type: "login",
        id: "ent-38",
        title: "Behance",
        notes: "Portfólio de inspiração.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "behanceportfolio",
        url: "https://behance.net",
      },
      {
        type: "login",
        id: "ent-39",
        title: "Dribbble",
        notes: "Mais inspirações visuais.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "johndoe_design",
        password: "dribbbleuiuxpass",
        url: "https://dribbble.com",
      },
      {
        type: "login",
        id: "ent-40",
        title: "Mastodon",
        notes: "Alternativa ao Twitter que nunca usei.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "johndoe@mastodon.social",
        password: "mastodon_password_9",
        url: "https://mastodon.social",
      },
      {
        type: "login",
        id: "ent-41",
        title: "Threads",
        notes: "Conta vinculada ao Instagram.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "@john.doe.dev",
        password: "Insta!Ph0t0!2026!",
        url: "https://threads.net",
      },
      {
        type: "login",
        id: "ent-42",
        title: "Strava",
        notes: "Monitoramento das corridas de final de semana.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "RunForestRun123!",
        url: "https://strava.com",
      },
      {
        type: "login",
        id: "ent-43",
        title: "Goodreads",
        notes: "Fins de leitura.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "booksaregood123",
        url: "https://goodreads.com",
      },
      {
        type: "login",
        id: "ent-44",
        title: "Tumblr",
        notes: "Fóssil da internet.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: true,
        createdAt: now(),
        updatedAt: now(),
        username: "blog_velho",
        password: "tumblr_pass_2012",
        url: "https://tumblr.com",
      },
      {
        type: "login",
        id: "ent-45",
        title: "Telegram Web",
        notes: "Canais de notícias de promoção.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "+5511999999999",
        password: "Telegram_Cloud_Pass",
        url: "https://web.telegram.org",
      },

      // Finanças e Bancos (46-55)
      {
        type: "login",
        id: "ent-46",
        title: "Nubank Web",
        notes: "Apenas para ver a fatura pelo PC.",
        foldersIds: ["folder-3", "folder-5"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "12345678909",
        password: "Nu#Password#8812",
        url: "https://nubank.com.br",
      },
      {
        type: "login",
        id: "ent-47",
        title: "Mercado Pago",
        notes: "Usado para transações do Mercado Livre.",
        foldersIds: ["folder-3"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "MP_Secure_Pass_26",
        url: "https://mercadopago.com.br",
      },
      {
        type: "login",
        id: "ent-48",
        title: "PayPal",
        notes: "Pagamentos internacionais.",
        foldersIds: ["folder-3"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "PayP@l_Str0ng_99x",
        url: "https://paypal.com",
      },
      {
        type: "login",
        id: "ent-49",
        title: "Banco Inter",
        notes: "Conta de investimentos.",
        foldersIds: ["folder-3", "folder-5"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "9876543-2",
        password: "Inter#Invest#98!",
        url: "https://bancointer.com.br",
      },
      {
        type: "login",
        id: "ent-50",
        title: "XP Investimentos",
        notes: "Renda fixa e fundos.",
        foldersIds: ["folder-3", "folder-5"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "john.xp.user",
        password: "XP_Brokerage_Password!",
        url: "https://xpi.com.br",
      },
      {
        type: "login",
        id: "ent-51",
        title: "Binance",
        notes: "Portfólio de Cripto (Hold).",
        foldersIds: ["folder-3", "folder-5"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "crypto_guy_john@gmail.com",
        password: "B1n4nc3_Crypto_#Secure",
        url: "https://binance.com",
      },
      {
        type: "login",
        id: "ent-52",
        title: "Metamask Extension",
        notes: "Senha do cofre local da extensão.",
        foldersIds: ["folder-3", "folder-5"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "local_wallet",
        password: "PasswordForWalletExt",
        url: "https://metamask.io",
      },
      {
        type: "login",
        id: "ent-53",
        title: "Wise",
        notes: "Conta multimoeda para viagens.",
        foldersIds: ["folder-3"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "W1s3_Tr4v3l_M0n3y",
        url: "https://wise.com",
      },
      {
        type: "login",
        id: "ent-54",
        title: "Serasa Experian",
        notes: "Para checar score de crédito.",
        foldersIds: ["folder-3"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "12345678909",
        password: "SerasaPassword!9",
        url: "https://serasa.com.br",
      },
      {
        type: "login",
        id: "ent-55",
        title: "Infomoney Newsletter",
        notes: "Cadastro só para ler notícias.",
        foldersIds: ["folder-3"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "senhafinanceira",
        url: "https://infomoney.com.br",
      },

      // E-Commerce e Lojas (56-65)
      {
        type: "login",
        id: "ent-56",
        title: "Amazon Brasil",
        notes: "Compras recorrentes Prime.",
        foldersIds: ["folder-2"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "Amzn_P_#Strong2026",
        url: "https://amazon.com.br",
      },
      {
        type: "login",
        id: "ent-57",
        title: "Mercado Livre",
        notes: "Entrega rápida.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "ML_Password_1298",
        url: "https://mercadolivre.com.br",
      },
      {
        type: "login",
        id: "ent-58",
        title: "AliExpress",
        notes: "Peças de hardware e mouses chineses.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "alipassword12345",
        url: "https://aliexpress.com",
      },
      {
        type: "login",
        id: "ent-59",
        title: "Shopee",
        notes: "Bugigangas variadas.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.cadastro.shopee",
        password: "shopeepassword",
        url: "https://shopee.com.br",
      },
      {
        type: "login",
        id: "ent-60",
        title: "Magalu",
        notes: "Eletrodomésticos.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "magalupassword!1",
        url: "https://magazineluiza.com.br",
      },
      {
        type: "login",
        id: "ent-61",
        title: "Kabum",
        notes: "Geralmente onde compro hardware para o PC.",
        foldersIds: ["folder-1", "folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "dev.master@empresa.com",
        password: "Kabum#Hardware#Pass",
        url: "https://kabum.com.br",
      },
      {
        type: "login",
        id: "ent-62",
        title: "Pichau",
        notes: "Comparativo de preços de hardware.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "pichaupassword",
        url: "https://pichau.com.br",
      },
      {
        type: "login",
        id: "ent-63",
        title: "Ifood",
        notes: "Uso no app, mas guardado aqui.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "ifood_password_app",
        url: "https://ifood.com.br",
      },
      {
        type: "login",
        id: "ent-64",
        title: "Zé Delivery",
        notes: "Sexta-feira à noite.",
        foldersIds: ["folder-2", "folder-4"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "zedeliverypass",
        url: "https://zedelivery.com.br",
      },
      {
        type: "login",
        id: "ent-65",
        title: "Submarino",
        notes: "Antiga, raramente usada.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "submarinopass",
        url: "https://submarino.com.br",
      },

      // Entretenimento e Streaming (66-75)
      {
        type: "login",
        id: "ent-66",
        title: "Netflix",
        notes: "Plano compartilhado com a família.",
        foldersIds: ["folder-4"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "familia.doe@gmail.com",
        password: "NetFlix#Family#2026",
        url: "https://netflix.com",
      },
      {
        type: "login",
        id: "ent-67",
        title: "Spotify",
        notes: "Plano Duo.",
        foldersIds: ["folder-4"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "Music_Is_Life_Spotify!",
        url: "https://spotify.com",
      },
      {
        type: "login",
        id: "ent-68",
        title: "Disney+",
        notes: "Assinatura via Mercado Livre.",
        foldersIds: ["folder-4"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "disneypassword99",
        url: "https://disneyplus.com",
      },
      {
        type: "login",
        id: "ent-69",
        title: "HBO Max / Max",
        notes: "Séries de domingo à noite.",
        foldersIds: ["folder-4"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "meu.email.pessoal@gmail.com",
        password: "MaxStreamingPass!",
        url: "https://max.com",
      },
      {
        type: "login",
        id: "ent-70",
        title: "Steam",
        notes: "Biblioteca de jogos enorme sem tempo para jogar.",
        foldersIds: ["folder-4"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "johndoe_gamer",
        password: "St34m_V3ry_Str0ng_P@ss!!",
        url: "https://store.steampowered.com",
      },
      {
        type: "login",
        id: "ent-71",
        title: "Epic Games Store",
        notes: "Só entro para pegar os jogos grátis.",
        foldersIds: ["folder-4"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "johndoe_freebies",
        password: "epicgamespassword1",
        url: "https://epicgames.com",
      },
      {
        type: "login",
        id: "ent-72",
        title: "PlayStation Network",
        notes: "Conta do PS5.",
        foldersIds: ["folder-4"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "john_psn_br",
        password: "PSN#Console#Secure",
        url: "https://playstation.com",
      },
      {
        type: "login",
        id: "ent-73",
        title: "Nintendo Online",
        notes: "Assinatura do Switch.",
        foldersIds: ["folder-4"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "nintendo_john",
        password: "mariopassword99",
        url: "https://nintendo.com",
      },
      {
        type: "login",
        id: "ent-74",
        title: "Crunchyroll",
        notes: "Animes da temporada.",
        foldersIds: ["folder-4"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "otaku_dev",
        password: "crunchypassword123",
        url: "https://crunchyroll.com",
      },
      {
        type: "login",
        id: "ent-75",
        title: "Duolingo",
        notes: "Ofensiva de 200 dias de inglês/japonês.",
        foldersIds: ["folder-2", "folder-4"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        username: "john_polyglot",
        password: "duolingopassword",
        url: "https://duolingo.com",
      },

      // ==========================================
      // CREDIT CARDS (15 itens: 76-90)
      // ==========================================
      {
        type: "card",
        id: "ent-76",
        title: "Nubank Violeta",
        notes: "Cartão principal de uso diário (crédito).",
        foldersIds: ["folder-3"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        holderName: "JOHN DOE",
        cardNumber: "4532  1122  3344  5566",
        password: "9981",
        expirationDate: "12/30",
        cvv: "123",
      },
      {
        type: "card",
        id: "ent-77",
        title: "Banco Inter Black",
        notes: "Usado para cashback e salas VIP.",
        foldersIds: ["folder-3"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        holderName: "JOHN DOE",
        cardNumber: "5411  9988  7766  5544",
        password: "1245",
        expirationDate: "05/29",
        cvv: "987",
      },
      {
        type: "card",
        id: "ent-78",
        title: "Itaú Click",
        notes: "Cartão reserva, backup na gaveta.",
        foldersIds: ["folder-3"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        holderName: "JOHN DOE",
        cardNumber: "4152  0011  2233  4455",
        password: "4431",
        expirationDate: "08/28",
        cvv: "555",
      },
      {
        type: "card",
        id: "ent-79",
        title: "XP Visa Infinite",
        notes: "Vinculado à conta de investimentos.",
        foldersIds: ["folder-3"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        holderName: "JOHN DOE",
        cardNumber: "4916  4433  2211  0099",
        password: "7762",
        expirationDate: "11/31",
        cvv: "432",
      },
      {
        type: "card",
        id: "ent-80",
        title: "Wise Debit Card",
        notes: "Cartão de débito internacional carregado com USD.",
        foldersIds: ["folder-3"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        holderName: "JOHN DOE",
        cardNumber: "4211  5566  7788  9900",
        password: "1102",
        expirationDate: "02/27",
        cvv: "888",
      },
      {
        type: "card",
        id: "ent-81",
        title: "Cartão de Débito Bradesco",
        notes: "Conta corrente antiga de salário.",
        foldersIds: ["folder-3"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        holderName: "JOHN DOE",
        cardNumber: "5013  2211  4433  6655",
        password: "3567",
        expirationDate: "04/26",
        cvv: "112",
      },
      {
        type: "card",
        id: "ent-82",
        title: "Amazon Prime Card",
        notes: "Dá 5% de cashback na Amazon.",
        foldersIds: ["folder-3"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        holderName: "JOHN DOE",
        cardNumber: "4532  9911  8822  7733",
        password: "1928",
        expirationDate: "09/31",
        cvv: "654",
      },
      {
        type: "card",
        id: "ent-83",
        title: "Mercado Pago Express",
        notes: "Cartão virtual para compras no ML.",
        foldersIds: ["folder-3"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        holderName: "JOHN DOE",
        cardNumber: "5241  3344  5566  7711",
        password: "0091",
        expirationDate: "01/30",
        cvv: "003",
      },
      {
        type: "card",
        id: "ent-84",
        title: "C6 Bank Carbon",
        notes: "Cancelado devido a cobrança de anuidade.",
        foldersIds: ["folder-3"],
        isFavorite: false,
        isDeleted: true,
        createdAt: now(),
        updatedAt: now(),
        holderName: "JOHN DOE",
        cardNumber: "5522  1100  9988  7766",
        password: "6541",
        expirationDate: "07/25",
        cvv: "741",
      }, // Exemplo deletado e vencido
      {
        type: "card",
        id: "ent-85",
        title: "Cartão Virtual Recorrente Netflix",
        notes: "Gerado no Nubank apenas para assinaturas.",
        foldersIds: ["folder-3", "folder-4"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        holderName: "JOHN DOE VIRTUAL",
        cardNumber: "4532  8888  1111  2222",
        password: "N/A",
        expirationDate: "12/29",
        cvv: "991",
      },
      {
        type: "card",
        id: "ent-86",
        title: "Digio Visa",
        notes: "Nunca usei, guardado por precaução.",
        foldersIds: ["folder-3"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        holderName: "JOHN DOE",
        cardNumber: "4003  2233  4455  6677",
        password: "8821",
        expirationDate: "06/28",
        cvv: "456",
      },
      {
        type: "card",
        id: "ent-87",
        title: "Neon Débito",
        notes: "Conta Neon zerada.",
        foldersIds: ["folder-3"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        holderName: "JOHN DOE",
        cardNumber: "5321  0099  8877  6655",
        password: "4311",
        expirationDate: "10/27",
        cvv: "321",
      },
      {
        type: "card",
        id: "ent-88",
        title: "Binance Crypto Card",
        notes: "Cartão pré-pago em cripto (Euro/BRL).",
        foldersIds: ["folder-3"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        holderName: "JOHN DOE",
        cardNumber: "4111  2222  3333  4444",
        password: "7070",
        expirationDate: "03/30",
        cvv: "909",
      },
      {
        type: "card",
        id: "ent-89",
        title: "Passai Corporate",
        notes: "Cartão corporativo para compras do escritório.",
        foldersIds: ["folder-1", "folder-3"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        holderName: "EMPRESA LTDA",
        cardNumber: "5422  8877  1122  3344",
        password: "4114",
        expirationDate: "08/29",
        cvv: "512",
      },
      {
        type: "card",
        id: "ent-90",
        title: "Cartão Alimentação Pluxee",
        notes: "Saldo do VR corporativo.",
        foldersIds: ["folder-1"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        holderName: "JOHN DOE",
        cardNumber: "6032  4455  6677  8899",
        password: "1337",
        expirationDate: "01/32",
        cvv: "000",
      },

      // ==========================================
      // SECURE NOTES (10 itens: 91-100)
      // ==========================================
      {
        type: "note",
        id: "ent-91",
        title: "Frase de Recuperação Metamask",
        notes: "NUNCA COMPARTILHE.",
        foldersIds: ["folder-5"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        name: "Seed Phrase Metamask",
        content:
          "apple banana cherry dog elephant fox grape horse ink jacket king lemon",
      },
      {
        type: "note",
        id: "ent-92",
        title: "Chave SSH Servidor Produção",
        notes: "Chave privada RSA para o servidor principal.",
        foldersIds: ["folder-1", "folder-5"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        name: "id_rsa_prod",
        content:
          "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtcn\n... [Truncated for Security] ...\n-----END OPENSSH PRIVATE KEY-----",
      },
      {
        type: "note",
        id: "ent-93",
        title: "Configurações de Roteador Wi-Fi",
        notes: "Dados do roteador da sala.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        name: "Router Home",
        content:
          "IP: 192.168.1.1\nAdmin User: admin\nAdmin Pass: SuperSecretRouterPass2026\nWi-Fi SSID: Casa_5G\nWi-Fi WPA2 Key: @BebamAgua2026",
      },
      {
        type: "note",
        id: "ent-94",
        title: "Dados da Empresa (CNPJ/Inscrição)",
        notes: "Para emissão de Notas Fiscais rápidas.",
        foldersIds: ["folder-1"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        name: "CNPJ Empresa",
        content:
          "Razão Social: John Doe Tech LTDA\nCNPJ: 12.345.678/0001-99\nInscrição Municipal: 987654-32\nBanco para Recebimento: PJ Nubank Ag 0001 CC 998822-1",
      },
      {
        type: "note",
        id: "ent-95",
        title: "Roteiro de Backup Emergencial",
        notes: "O que fazer se tudo cair.",
        foldersIds: ["folder-5"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        name: "Disaster Recovery",
        content:
          "1. Baixar snapshot criptografado do S3.\n2. Usar a chave privada do cofre físico B para descriptografar.\n3. Subir a stack via script deploy-emergency.sh.",
      },
      {
        type: "note",
        id: "ent-96",
        title: "Tokens de API de Teste",
        notes: "Chaves sandbox expirando logo.",
        foldersIds: ["folder-1"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        name: "Stripe Sandbox Token",
        content: "sk_test_51Nx...fakeTokenString...8821j",
      },
      {
        type: "note",
        id: "ent-97",
        title: "Combinação do Cofre Físico",
        notes: "Cofre do guarda-roupa.",
        foldersIds: ["folder-5"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        name: "Cofre Quarto",
        content:
          "Girar 3 vezes para a direita até o 40, 2 vezes para a esquerda até o 15, 1 vez para a direita até o 65.",
      },
      {
        type: "note",
        id: "ent-98",
        title: "Informações de Saúde / Tipo Sanguíneo",
        notes: "Dados úteis para emergências.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        name: "Ficha Médica",
        content:
          "John Doe\nTipo Sanguíneo: O Positivo\nAlergias: Penicilina e Frutos do Mar.\nPlano de Saúde: Unimed - Carteirinha 0021 9982 1122 001",
      },
      {
        type: "note",
        id: "ent-99",
        title: "Rascunho de Ideia de Startup",
        notes: "Uber para passeadores de furões.",
        foldersIds: ["folder-2"],
        isFavorite: false,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        name: "Projeto Secreto Furoes",
        content:
          "Validar mercado em SP e Curitiba. Modelo de assinatura mensal. MVP usando apenas um grupo no WhatsApp e automação com n8n.",
      },
      {
        type: "note",
        id: "ent-100",
        title: "Códigos de Backup Discord (2FA)",
        notes: "Códigos de uso único salvos em caso de perda do celular.",
        foldersIds: ["folder-5"],
        isFavorite: true,
        isDeleted: false,
        createdAt: now(),
        updatedAt: now(),
        name: "Discord 2FA Recovery",
        content:
          "Código 1: abcd-1234\nCódigo 2: efgh-5678\nCódigo 3: ijkl-9012\nCódigo 4: mnop-3456\nCódigo 5: qrst-7890",
      },
    ],
  };
};
